[package]
name = "ls"
version = "0.1.0"
authors = ["lohxx <lohanna.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
console = "0.9.0"